import { createUseStyles } from 'react-jss'
import { theme } from '../theme'

export const useContactStyles = createUseStyles({
  section: {
    padding: '3rem 1rem',
    backgroundColor: theme.colors.white,
    '@media (min-width: 768px)': {
      padding: '5rem 1.5rem',
    },
  },
  container: {
    maxWidth: '896px',
    margin: '0 auto',
  },
  title: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: theme.colors.gray[900],
    marginBottom: '1.5rem',
    textAlign: 'center',
    '@media (min-width: 768px)': {
      fontSize: '2.25rem',
      marginBottom: '2.5rem',
    },
  },
  card: {
    backgroundColor: theme.colors.blue[50],
    padding: '1rem',
    borderRadius: '0.5rem',
    borderLeft: `4px solid ${theme.colors.medicalBlue}`,
    boxShadow: theme.shadows.sm,
    '@media (min-width: 768px)': {
      padding: '2rem',
    },
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.5rem',
    '@media (min-width: 768px)': {
      marginBottom: '2rem',
    },
  },
  iconContainer: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '3rem',
    height: '3rem',
    backgroundColor: theme.colors.medicalBlue,
    borderRadius: '50%',
    marginBottom: '0.75rem',
    '@media (min-width: 768px)': {
      width: '4rem',
      height: '4rem',
      marginBottom: '1rem',
    },
  },
  icon: {
    color: theme.colors.white,
    width: '1.5rem',
    height: '1.5rem',
    '@media (min-width: 768px)': {
      width: '2rem',
      height: '2rem',
    },
  },
  cardTitle: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    color: theme.colors.gray[900],
    marginBottom: '0.75rem',
    '@media (min-width: 768px)': {
      fontSize: '1.5rem',
      marginBottom: '1rem',
    },
  },
  cardText: {
    fontSize: '0.875rem',
    color: theme.colors.gray[700],
    lineHeight: '1.75',
    maxWidth: '672px',
    margin: '0 auto 1rem',
    padding: '0 0.5rem',
    '@media (min-width: 768px)': {
      fontSize: '1.125rem',
      marginBottom: '1.5rem',
    },
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'center',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: theme.colors.medicalBlue,
    color: theme.colors.white,
    padding: '0.75rem 1.5rem',
    borderRadius: '0.5rem',
    fontWeight: 600,
    fontSize: '1rem',
    textDecoration: 'none',
    boxShadow: theme.shadows.md,
    transition: 'all 0.2s',
    '&:hover': {
      backgroundColor: theme.colors.blue[700],
      boxShadow: theme.shadows.lg,
    },
    '@media (min-width: 768px)': {
      gap: '0.75rem',
      padding: '1rem 2rem',
      fontSize: '1.125rem',
    },
  },
  buttonIcon: {
    width: '1rem',
    height: '1rem',
    '@media (min-width: 768px)': {
      width: '1.25rem',
      height: '1.25rem',
    },
  },
  findFamiliesSection: {
    marginTop: '2.5rem',
    padding: '1.5rem 1rem',
    backgroundColor: theme.colors.white,
    borderRadius: '0.5rem',
    boxShadow: theme.shadows.sm,
    border: `1px solid ${theme.colors.gray[200]}`,
    '@media (min-width: 768px)': {
      padding: '2rem',
    },
  },
  findFamiliesTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: theme.colors.gray[900],
    marginBottom: '0.5rem',
  },
  findFamiliesText: {
    fontSize: '0.875rem',
    color: theme.colors.gray[700],
    lineHeight: 1.7,
    marginBottom: '1rem',
  },
  findFamiliesButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    padding: '0.5rem 1.5rem',
    backgroundColor: theme.colors.white,
    color: theme.colors.medicalBlue,
    border: `1px solid ${theme.colors.medicalBlue}`,
    fontWeight: 600,
    fontSize: '0.95rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    '&:hover': {
      backgroundColor: theme.colors.medicalBlue,
      color: theme.colors.white,
    },
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '1rem',
  },
  modal: {
    width: '100%',
    maxWidth: '32rem',
    backgroundColor: theme.colors.white,
    borderRadius: '0.75rem',
    boxShadow: theme.shadows.lg,
    padding: '1.5rem',
    '@media (min-width: 768px)': {
      padding: '2rem',
    },
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.75rem',
  },
  modalTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: theme.colors.gray[900],
  },
  modalClose: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '1.1rem',
    color: theme.colors.gray[400],
    '&:hover': {
      color: theme.colors.gray[600],
    },
  },
  modalDescription: {
    fontSize: '0.85rem',
    color: theme.colors.gray[600],
    lineHeight: 1.6,
    marginBottom: '1rem',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
    },
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    fontSize: '0.8rem',
    color: theme.colors.gray[700],
    flex: 1,
    gap: '0.25rem',
  },
  input: {
    padding: '0.55rem 0.7rem',
    borderRadius: '0.5rem',
    border: `1px solid ${theme.colors.gray[300]}`,
    fontSize: '0.9rem',
    outline: 'none',
    '&:focus': {
      borderColor: theme.colors.medicalBlue,
      boxShadow: `0 0 0 1px ${theme.colors.medicalBlue}`,
    },
  },
  checkboxGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginTop: '0.5rem',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    fontSize: '0.85rem',
    color: theme.colors.gray[700],
    '& input': {
      marginTop: '0.15rem',
    },
  },
  errorText: {
    fontSize: '0.8rem',
    color: theme.colors.red?.[600] || '#dc2626',
  },
  successText: {
    fontSize: '0.8rem',
    color: theme.colors.green?.[600] || '#16a34a',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.75rem',
    marginTop: '1rem',
  },
  secondaryButton: {
    padding: '0.5rem 1rem',
    borderRadius: '9999px',
    border: `1px solid ${theme.colors.gray[300]}`,
    backgroundColor: theme.colors.white,
    color: theme.colors.gray[700],
    fontSize: '0.9rem',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: theme.colors.gray[50],
    },
  },
  primaryButton: {
    padding: '0.5rem 1.25rem',
    borderRadius: '9999px',
    border: 'none',
    backgroundColor: theme.colors.medicalBlue,
    color: theme.colors.white,
    fontSize: '0.9rem',
    fontWeight: 600,
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: theme.colors.blue[700],
    },
  },
});
